name: fruits_app
description: Online Fruits shopping app UI
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  flutter_staggered_grid_view: ^0.3.1
  path_provider: ^1.6.11
  font_awesome_flutter: ^8.8.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/